spring.application.name=empCRUD
spring.datasource.url=jdbc:postgresql://localhost:5432/employee
spring.datasource.username=postgres
spring.datasource.password=fkr@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Security
#spring.security.user.name=fkre
#spring.security.user.password=fkre123

# JWT configuration
jwt.secret=mySuperSecretKeyForJwtAuthentication1234567890!@#$%
jwt.expiration=36000